*** Variables ***
${SITE}                     http://www.jouse.com.br
${NAVEGADOR}                Chrome
${COMPRE AGORA}             css=.jss24:nth-child(2) > .jss14
${SELECAO_COR}              css=.jss77:nth-child(2) .jss86:nth-child(2) > .
${SELECAO_ACABAMENTO}       css=.jss77:nth-child(3) .jss86:nth-child(2) > :
${COMPRE AGORA_POS_COR}     css=.jss28
${CONFIRMAR_COMPRA}         css=.jss166 .jss28

*** Keywords ***


